/**
 * These are the constants used in the TrustAuth addon. This is browser independent code.
 *
 * @author Daniel Fox
 * @link trustauth.com
 * @license BSD-3 Clause License http://opensource.org/licenses/BSD-3-Clause
 *
 * Copyright (c) 2012, Daniel Fox
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
 *
 *     Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
 *     Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the
 *         documentation and/or other materials provided with the distribution.
 *     Neither the name of TrustAuth nor the names of its contributors may be used to endorse or promote products derived from this software
 *         without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
var EXPORTED_SYMBOLS = [
  'TRUSTAUTH_AJAX_LOADER',
  'TRUSTAUTH_LOGO',
  'TRUSTAUTH_LOGO_DISABLED',
  'TRUSTAUTH_CHALLENGE_ID',
  'TRUSTAUTH_RESPONSE_ID',
  'TRUSTAUTH_REGISTER_ID',
  'TRUSTAUTH_KEY_ID',
  'FIREFOX_BUTTON_ID',
  'FIREFOX_UNLOCK_ID',
  'FIREFOX_CHANGE_PASSWORD_ID',
  'TIMEOUT',
  'HASH_LENGTH',
  'MESSAGE_TYPE',
  'CACHE_KEY_COUNT',
  'ITERATION_COUNT',
  'KEY_LENGTH',
  'ENCRYPTION_KEY_LENGTH',
  'SALT_IDS',
  'SALT_LENGTH',
  'SALTS',
  'DEMO_SITE_PUBLIC_KEY',
  'DEMO_SITE_PRIVATE_KEY',
  'IDLE_TIMEOUT_INTERVAL',
  'KEY_LENGTHS',
  'EXPONENT',
  'DEFAULT_KEY_LENGTH',
  'BASE64_LOGO',
];

var TRUSTAUTH_AJAX_LOADER   = 'chrome://trustauth/skin/ajax-loader.gif';
var TRUSTAUTH_LOGO          = 'chrome://trustauth/skin/logo_small_shorter_22.png';
var TRUSTAUTH_LOGO_DISABLED = 'chrome://trustauth/skin/logo_small_shorter_disabled_22.png';

var TRUSTAUTH_CHALLENGE_ID = "trustauth-challenge";
var TRUSTAUTH_RESPONSE_ID  = "trustauth-response";
var TRUSTAUTH_REGISTER_ID  = "trustauth-register";
var TRUSTAUTH_KEY_ID       = "trustauth-key";

var FIREFOX_BUTTON_ID          = 'trustauth-main-button';
var FIREFOX_UNLOCK_ID          = 'trustauth-menu-unlock';
var FIREFOX_CHANGE_PASSWORD_ID = 'trustauth-menu-change-password';

var TIMEOUT = 30; // The length of time a message will be valid in seconds

var HASH_LENGTH = 32;

var MESSAGE_TYPE = {
  'challenge': 0,
  'response' : 1,
};

var CACHE_KEY_COUNT = 2;

var ITERATION_COUNT = 2048;

var KEY_LENGTH = 32; // 256 bits
var ENCRYPTION_KEY_LENGTH = 32; // 256 bits

var SALT_IDS   = { 'ENC_KEY': 1, 'STORAGE': 2, 'PASSWORD': 3 };
var SALT_LENGTH = 32; // 256 bits

var SALTS = { 'ENC_KEY': null, 'STORAGE': null, 'PASSWORD': null };

var DEMO_SITE_PUBLIC_KEY  = "-----BEGIN PUBLIC KEY-----\n" +
"MIGdMA0GCSqGSIb3DQEBAQUAA4GLADCBhwKBgQCVoeQxVmYsm9expDrr+14rbxtv\n" +
"wL58Qlr/HkG4H/CW8DjnNUte2W2rLZXUlN62kJCaqsz5LgvPCKftbX0CQTdLQuOC\n" +
"/uMOiirgtBrA02XFzMD7LR296T6gjXTrsIMm9aGdVlRyGp5wIxw73uQy4gUUjQYM\n" +
"NgeXamudQvniZVWPUwIBAw==\n" +
"-----END PUBLIC KEY-----";
var DEMO_SITE_PRIVATE_KEY = "-----BEGIN RSA PRIVATE KEY-----\n" +
"MIICWgIBAAKBgQCVoeQxVmYsm9expDrr+14rbxtvwL58Qlr/HkG4H/CW8DjnNUte\n" +
"2W2rLZXUlN62kJCaqsz5LgvPCKftbX0CQTdLQuOC/uMOiirgtBrA02XFzMD7LR29\n" +
"6T6gjXTrsIMm9aGdVlRyGp5wIxw73uQy4gUUjQYMNgeXamudQvniZVWPUwIBAwKB\n" +
"gGPBQsuO7shn5SEYJ0f86XJKEkqAfv2Bkf9pgSVqoGSgJe943OnmSRzJDo24lHm1\n" +
"tbxx3ft0B99bGp5I/gGAz4Z7J6pq/LZmSC1IQi45vMhLPqdmeWJzgrHSD35e9MCn\n" +
"kIo6/ZAXUIR/9NMiBJCiQ5d+NWCtcB+veWnKUsB1lo4LAkEA3C8/QtW0FWTAyAOJ\n" +
"8CMaDphJSPKfImpNNeJiHs2vZF61z83/KCYTKpYBl1SRTA1+5mtaqQIQxyk5y/BY\n" +
"QPyVmwJBAK34xBuSSNtZ2/+z8Yynf01Ktsp1CxmQSJx7TANGVpXqGC4KGs9/ljiW\n" +
"/ZSIyKKSMmlKoIjdVxwMRMeNaXP3JKkCQQCSyiosjngOQyswAlv1bLwJutuF9xTB\n" +
"nDN5QZa/M8pC6c6KiVTFbrdxuVZk4wuICP9ER5HGAWCExiaH9ZArUw5nAkBz+y1n\n" +
"tts85pKqd/ZdxP+I3HncTgdmYDBoUjKs2Y8OnBAesWc0/7l7D1O4WzBsYXbw3GsF\n" +
"6OS9XYMvs5uipMMbAkAdhhQFPpIkrxT6zvof6RSMlh+2PzrEfGrxmgug9cLp/8Lu\n" +
"JXa4T8LWsoaLyQwAR4Xbazy2W+vXkbeSK1m48mHV\n" +
"-----END RSA PRIVATE KEY-----";

var IDLE_TIMEOUT_INTERVAL = 60; // In seconds

var KEY_LENGTHS = { 1: 1024, 2: 2048, 3: 4096 }; // Lengths in bits
var EXPONENT    = 3;
var DEFAULT_KEY_LENGTH = 2048;

//'R0lGODlhMAAwAPcAAP//////zP//mf//Zv//M///AP/M///MzP/Mmf/MZv/MM//MAP+Z//+ZzP+Zmf+ZZv+ZM/+ZAP9m//9mzP9mmf9mZv9mM/9mAP8z//8zzP8zmf8zZv8zM/8zAP8A//8AzP8Amf8AZv8AM/8AAMz//8z/zMz/mcz/Zsz/M8z/AMzM/8zMzMzMmczMZszMM8zMAMyZ/8yZzMyZmcyZZsyZM8yZAMxm/8xmzMxmmcxmZsxmM8xmAMwz/8wzzMwzmcwzZswzM8wzAMwA/8wAzMwAmcwAZswAM8wAAJn//5n/zJn/mZn/Zpn/M5n/AJnM/5nMzJnMmZnMZpnMM5nMAJmZ/5mZzJmZmZmZZpmZM5mZAJlm/5lmzJlmmZlmZplmM5lmAJkz/5kzzJkzmZkzZpkzM5kzAJkA/5kAzJkAmZkAZpkAM5kAAGb//2b/zGb/mWb/Zmb/M2b/AGbM/2bMzGbMmWbMZmbMM2bMAGaZ/2aZzGaZmWaZZmaZM2aZAGZm/2ZmzGZmmWZmZmZmM2ZmAGYz/2YzzGYzmWYzZmYzM2YzAGYA/2YAzGYAmWYAZmYAM2YAADP//zP/zDP/mTP/ZjP/MzP/ADPM/zPMzDPMmTPMZjPMMzPMADOZ/zOZzDOZmTOZZjOZMzOZADNm/zNmzDNmmTNmZjNmMzNmADMz/zMzzDMzmTMzZjMzMzMzADMA/zMAzDMAmTMAZjMAMzMAAAD//wD/zAD/mQD/ZgD/MwD/AADM/wDMzADMmQDMZgDMMwDMAACZ/wCZzACZmQCZZgCZMwCZAABm/wBmzABmmQBmZgBmMwBmAAAz/wAzzAAzmQAzZgAzMwAzAAAA/wAAzAAAmQAAZgAAMwAAADQ4PTM3PDE1OjA0OS8zOC4yNy0xNiwwNSsvNCouMyktMiMELRQBHyodNDQrPCAZKi0sNyMlKzI2OzY6Pz1AQ4GEhwQSHS0yNi80ODg9QRIYHHp9f73Bwy42NzE5Ois0M0VLSmZvaldhWytEMRgtGyM+JixULlmzWSwAAAAAMAAwAAAI/wABAFhHsKDBddgSKlzIEFu2hxCzqZtIUZtFbQIHsjtYsKFHhREjUpx4UZu6dRjXbeSI8KPHkBBHqitpcds6m/E4unwJU+JImjW3abOpcyfDnj4rAt3GlClBo0hlqns402JVmk2zIozHrqvXr2DDdo03MZ7ZeNiWZmUKb108ce7iyp1Lt25cedm0nSO3V9zVtWy5cVvHTV++w4gTK158ONBEfYEg4/M2E/A2eIK5sXNnZQW9z6BDix69wsq1fFDq1IGy51w2wJgza+bsebRt26Wv7anzr/e/fejUZY0tO548K7eTj253j7fvf6bG2Qssm1u3bgnx4QuLL9080O3Sbf8Hi49cPud7eoNKR132dezrxMmbT19eumvfP8+7lq7+/Gvj7AadKb75U4491b13XUJunWWWSu60A9p+KxUUTzn6OOdPOr6BIp17CmJ3FFXxXCOhftfEI9RF9gTI2x7yjPOJb/ego411IXbzzogkmjhhiitqk404+DhnCjnlENhbdPbkqKM3IIWkTokn0rOfijVhY55z/ZzDTT0dehniO96UmVBPU/qIIpZD1VOOgKCQ802LoBRYTj3vkVmmN1FpQ+WPKm7DDTbnZLgkOfXYk6Rv0Wnz5J5lojnTn2vCw1SLAv7DzznqwNMNOM+Jgw48kJb5jZQVUWplitxsg4047Dj/F+c723RDJ6Pj1FPqN6fGNNI2ql7ZqpbnHdpkN2760+E4pJrKa68y1RQsq9q886Zz9un63pu+7XPns88mRZK0aq4aDzf2FCorOfa06+6iS+YKLq8/lQRsuVfaSk6m0VxDzr8Ak8PPc+mg8w644Chl77TrwAMONun1Zhhj+UQMnby8gpMwUENxw7A9W/qm2sgkq7bswRprzDFTHuN7zTr1uPjczDR3W847KYODVVMtV0nhOUXWLPRz0dWjcTjh2JtVz4Dua+Q1/EQt9dTuKNtba0cjHdRag7msjjkWy0NOOueUbXbZZJ/znD/j3IN00pZ5uo7LGK5bTz3w3K333e+0/6jkPx6+8zZsgnUzt8/XXNubP4h6M2/G4NxTjtW99VOO2+GsRZzhLgf9zx7kiNPN45B/Aw638botTlPEFX74j8VChyjpOUc+zt+gnIP06pdVx807r6NocT8YI5xzOJLvs/Y594jTeuHdeHN4bfN4Hqc4Bz9b+9vhfCPjss37/p70+GZ6ZD3Gp8w98rc/10864YCo4DZE6mN/PKb4o7992W+//u730J/++AG/zDjJG9y4zzWuITaApQMckFPf/8IhjgoG7BwVxNGYTOWqhHxJbyg73gQpWEFx3OOEzaugk/S0J9NBcF7++18JZ0hD0SmIhZCinQgnWMMeig5HOHTW4zNiuD4f+rAb2YheqRw3xB3K0Ig0/IY4APAOdShRiDB0IvegWEMpZsQbLNShBHnIxRoKJCAAOw==';
var BASE64_LOGO = 'R0lGODlhEAAQAOYAAAAAAAAAABIAJBgAJBwAKBwJJh4JKAYMEwASDSASKR0TJRUZHx4ZKRYbICEbKRkcHxocIiofMx4iJCAiJiIlKR0oIiQpLCIqJyksMC0wMx8yIjAzNh04HSI5KDg6PSI7IzJANUBARyFBHz5DQ0RHSDlIOylJJzNJNEVKSzdMOUlNTSxUKFNUVTpXOidYHjtcOS9eKTZeMjFkKjRoLDtxNHZzfXp2gTZ4KXZ6fDp7Ljp9M3l9f3p+gIKFiEuGQT+HMEOINX2LgD6MLpSQmT6RKUKTMUiXNkWbMZqboD+dI02dPFCfQZ2ipEqjNk6kO1KlQqClp6CmqFCnPaWqrE6rOVCrPKiur6musV24SAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAkKAFkAIf8LSUNDUkdCRzEwMTL/AAAHqGFwcGwCIAAAbW50clJHQiBYWVogB9kAAgAZAAsAGgALYWNzcEFQUEwAAAAAYXBwbAAAAAAAAAAAAAAAAAAAAAAAAPbWAAEAAAAA0y1hcHBsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALZGVzYwAAAQgAAABvZHNjbQAAAXgAAAVsY3BydAAABuQAAAA4d3RwdAAABxwAAAAUclhZWgAABzAAAAAUZ1hZWgAAB0QAAAAUYlhZWgAAB1gAAAAUclRSQwAAB2wAAAAOY2hhZAAAB3wAAAAsYlRSQwAAB2wAAAAOZ1RS/0MAAAdsAAAADmRlc2MAAAAAAAAAFEdlbmVyaWMgUkdCIFByb2ZpbGUAAAAAAAAAAAAAABRHZW5lcmljIFJHQiBQcm9maWxlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABtbHVjAAAAAAAAAB4AAAAMc2tTSwAAACgAAAF4aHJIUgAAACgAAAGgY2FFUwAAACQAAAHIcHRCUgAAACYAAAHsdWtVQQAAACoAAAISZnJGVQAAACgAAAI8emhUVwAAABYAAAJkaXRJVAAAACgAAAJ6bmJOTwAAACYAAAKia29LUgAAABYAAP8CyGNzQ1oAAAAiAAAC3mhlSUwAAAAeAAADAGRlREUAAAAsAAADHmh1SFUAAAAoAAADSnN2U0UAAAAmAAAConpoQ04AAAAWAAADcmphSlAAAAAaAAADiHJvUk8AAAAkAAADomVsR1IAAAAiAAADxnB0UE8AAAAmAAAD6G5sTkwAAAAoAAAEDmVzRVMAAAAmAAAD6HRoVEgAAAAkAAAENnRyVFIAAAAiAAAEWmZpRkkAAAAoAAAEfHBsUEwAAAAsAAAEpHJ1UlUAAAAiAAAE0GFyRUcAAAAmAAAE8mVuVVMAAAAmAAAFGGRhREsAAAAuAAAFPgBWAWEAZQBvAGIAZQD/YwBuAP0AIABSAEcAQgAgAHAAcgBvAGYAaQBsAEcAZQBuAGUAcgBpAQ0AawBpACAAUgBHAEIAIABwAHIAbwBmAGkAbABQAGUAcgBmAGkAbAAgAFIARwBCACAAZwBlAG4A6AByAGkAYwBQAGUAcgBmAGkAbAAgAFIARwBCACAARwBlAG4A6QByAGkAYwBvBBcEMAQzBDAEOwRMBD0EOAQ5ACAEPwRABD4ERAQwBDkEOwAgAFIARwBCAFAAcgBvAGYAaQBsACAAZwDpAG4A6QByAGkAcQB1AGUAIABSAFYAQpAadSgAIABSAEcAQgAggnJfaWPPj/AAUAByAG8AZgBp/wBsAG8AIABSAEcAQgAgAGcAZQBuAGUAcgBpAGMAbwBHAGUAbgBlAHIAaQBzAGsAIABSAEcAQgAtAHAAcgBvAGYAaQBsx3y8GAAgAFIARwBCACDVBLhc0wzHfABPAGIAZQBjAG4A/QAgAFIARwBCACAAcAByAG8AZgBpAGwF5AXoBdUF5AXZBdwAIABSAEcAQgAgBdsF3AXcBdkAQQBsAGwAZwBlAG0AZQBpAG4AZQBzACAAUgBHAEIALQBQAHIAbwBmAGkAbADBAGwAdABhAGwA4QBuAG8AcwAgAFIARwBCACAAcAByAG8AZgBpAGxmbpAaACAAUgBHAEIAIGPPj//wZYdO9k4AgiwAIABSAEcAQgAgMNcw7TDVMKEwpDDrAFAAcgBvAGYAaQBsACAAUgBHAEIAIABnAGUAbgBlAHIAaQBjA5MDtQO9A7kDugPMACADwAPBA78DxgOvA7sAIABSAEcAQgBQAGUAcgBmAGkAbAAgAFIARwBCACAAZwBlAG4A6QByAGkAYwBvAEEAbABnAGUAbQBlAGUAbgAgAFIARwBCAC0AcAByAG8AZgBpAGUAbA5CDhsOIw5EDh8OJQ5MACAAUgBHAEIAIA4XDjEOSA4nDkQOGwBHAGUAbgBlAGwAIABSAEcAQgAgAFAAcgBvAGYAaQBsAGkAWQBsAGX/AGkAbgBlAG4AIABSAEcAQgAtAHAAcgBvAGYAaQBpAGwAaQBVAG4AaQB3AGUAcgBzAGEAbABuAHkAIABwAHIAbwBmAGkAbAAgAFIARwBCBB4EMQRJBDgEOQAgBD8EQAQ+BEQEOAQ7BEwAIABSAEcAQgZFBkQGQQAgBioGOQYxBkoGQQAgAFIARwBCACAGJwZEBjkGJwZFAEcAZQBuAGUAcgBpAGMAIABSAEcAQgAgAFAAcgBvAGYAaQBsAGUARwBlAG4AZQByAGUAbAAgAFIARwBCAC0AYgBlAHMAawByAGkAdgBlAGwAcwBldGV4dAAAAABDb3B5cmlnaHQgMjAwrzcgQXBwbGUgSW5jLiwgYWxsIHJpZ2h0cyByZXNlcnZlZC4AWFlaIAAAAAAAAPNSAAEAAAABFs9YWVogAAAAAAAAdE0AAD3uAAAD0FhZWiAAAAAAAABadQAArHMAABc0WFlaIAAAAAAAACgaAAAVnwAAuDZjdXJ2AAAAAAAAAAEBzQAAc2YzMgAAAAAAAQxCAAAF3v//8yYAAAeSAAD9kf//+6L///2jAAAD3AAAwGwALAAAAAAQABAAAAfPgBQZGISFGBaIiRIWEBALjQ2PFAyJFBQbKiiamiokGyUYlpYsU6VXU1FWQz5YMQUWlhkjIx5RPRkhI0pFQhCiFBANB0w4AQI0Rh1NJgmwFocSTDwBEUs3A0c5BM6IENIBLVQcAjNHE5aJ3jsBPk0nKS9UMAaV6ghPTU5STlQ/9LDAmNRwUUWEhg8VZDj5oEAUBCg2iAAZQMFBAgdNromSgCRIkhXNKFwYoOOIhF8eQHw4SWHCBAgVVv5qAMFBS5cSJEBQ8FIUopsTcuac8CAQADs=';
